image: python:3.12-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache

stages:
  - test
  - release

before_script:
  - export PIP_CACHE_DIR="$CI_PROJECT_DIR/.pip-cache"
  - mkdir -p "$PIP_CACHE_DIR"
  - python -m pip install --upgrade pip

test:
  stage: test
  script:
    - python -m pip install -e .[stt,test]
    - python -m pytest

release:
  stage: release
  only:
    - tags
  script:
    - python -m pip install -e .[stt,test,build]
    - python -m pytest
    - python -m build
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week
